### PR TITLE
docs: grunt-jsonschema-faker plugin info added

### PR DESCRIPTION
**Pull request by tkoomzaaskz**
I've created a dedicated grunt plugin using `json-schema-faker`.

### CODE REVIEW

**Comment by tkoomzaaskz** [comment]
this is a lie :) in fact, there is a dependency failing that fails entire test and it's undeterministic unfortunately. See the test details.

**Comment by pateketrueke** [comment]
I've experienced the same issue with `npm install`, sometimes it fails, then rerun `npm install` and works again. :beers:

If it happens again please don't open the same PR twice, I'll check the tests before any merge anyway.

**Comment by tkoomzaaskz** [comment]
Uhm, sorry if I misunderstood you - but this is just few lines being added to the main readme. There were two commits with the same message (maybe that was a mistake): first one has added the grunt plugin link to the online demo (json-schema-faker.js.org) and it has been merged, whereas the second one (this one - #26) adds a paragraph to the readme. And it hasn't been merged.

*Those are two different things, although I gave them the same git commit message*. Mea culpa :/

**Comment by pateketrueke** [comment]
Oh damn, I didn't notice it before closing this.

Sorry for this, indeed I was thinking in both PR as the same thing.

**Comment by tkoomzaaskz** [comment]
No problem at all, thanks!

**Pull request merged**
